installing and deploying cloudy in several instances
Clommunity/cloudynitzar pull request #17
Opened 2019-03-12 19:28 UTC by ismferd

Hi again,

in order to install cloudy in several instances, I want to add an Ansible script to do that.

2019-03-15 15:08 UTC, ismferd commented
@rogerpueyo ☝️ , when you can of course

2019-03-17 11:23 UTC, rogerpueyo requested changes
Please check the comments,

Thanks,
Roger

2019-03-17 11:23 UTC, rogerpueyo commented on README.md
> +If you want to "cloudinizer" a few machines then you should add hostnames in host file and launch:
Can you please better explain this step?

2019-03-17 11:23 UTC, rogerpueyo commented on README.md
> +**NOTE:** For go ahead with this step you will need [Ansible](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html)
To proceed with/Before going ahead with/To perform

2019-03-17 12:09 UTC, ismferd commented
Sure, 
Can you check it again?  thanks @rogerpueyo

2019-03-27 17:42 UTC, ismferd commented
@rogerpueyo , I checked your comments and I added info

2020-11-09 13:43 UTC, merged